name: Push to ECR
on:
  push:
    branches:
      - master
jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: 3.0.0
