name: Push to ECR
on:
  push:
    branches:
      - master
jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR with AWS CLI
        id: login-ecr-aws-cli
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
          aws configure set region "${{ secrets.AWS_REGION }}"
      - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@9a10af1be5e3eb7931f48c0290364a131e7ecd70
        uses: pietrobolcato/install-azure-cli-action@v1.0.1
      - name: AZ Login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENTID }} -p ${{ secrets.AZURE_CRED }} --tenant ${{ secrets.AZURE_TENANTID }}
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: latest
      - name: createing helm charts
        run: helm create msa-dev-helm
      - name: helm package 
        run: helm package msa-dev-helm
      - name: Tagging
        run: docker tag msa-dev-helm.tgz totemtest.azurecr.io/TOTEMTEST/msa-dev-helm:latest
      - name: Push to Acr
        run: docker push totemtest.azurecr.io/TOTEMTEST/msa-dev-helm:latest
      - name: Pull Helm repo
        run: helm pull totemtest.azurecr.io/TOTEMTEST/msa-dev-helm:latest
      - name: Tagging
        run: docker tag totemtest.azurecr.io/TOTEMTEST/msa-dev-helm:latest 554487920627.dkr.ecr.us-east-1.amazonaws.com/totem:latest
      - name: Push to ECR
        run: docker push 554487920627.dkr.ecr.us-east-1.amazonaws.com/totem:latest
