name: Push to ECR

on:
  push:
    branches:
           - main
      

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Download secure file
        run: echo "${{ secrets.SECRET_NAME }}" > server.xml 

      - name: Setup SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: ${{ secrets.ORG }}
          project: ${{ secrets.PRO }}
          token: ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
