name: Push to ECR
on:
  push:
    branches:
      - master
jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: latest
      - name: Checkout code
        uses: actions/checkout@v2
      - name: awslogin
        run: 
          source helm.bash
          awsLogin "${{ secrets.AWS_ACCESS_KEY_ID }}" "${{ secrets.AWS_SECRET_ACCESS_KEY }}" "${{ secrets.AWS_SESSION_TOKEN }}" "${{ secrets.AWS_REGION }}"
      - name: azure login
        run: 
          source helm.bash
          azureLogin ${{ secrets.AZURE_CLIENTID }} ${{ secrets.AZURE_CRED }} ${{ secrets.AZURE_TENANTID }}
      - name: helm push
        run:
          source helm.bash
          helmpush
        
