name: Push to ECR

on:
  push:
    branches:
           - release
      

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
         version: 3.0.0
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
      - name: Log in to Amazon ECR with AWS CLI
        id: login-ecr-aws-cli
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
          aws configure set region "${{ secrets.AWS_REGION }}"
          aws ecr get-login-password | docker login --username AWS --password-stdin "${{ secrets.AWS_REGISTRY_URL }}"
        env:
          AWS_REGION: "${{ secrets.AWS_REGION }}"
          AWS_REGISTRY_URL: "${{ secrets.AWS_REGISTRY_URL }}"
        continue-on-error: true
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name <eks-cluster-name> --region <aws-region>
      
      - name: Test kubectl command
        run: kubectl get pods
