name: Push to ECR

on:
  push:
    branches:
           - main
      

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Download secure file
        run: echo "${{ secrets.SECRET_NAME }}" > server.xml 

      - name: Setup SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: ${{ secrets.ORG }}
          project: ${{ secrets.PRO }}
          token: ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: maven/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./java-maven

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./java-maven/target/my-artifact.jar
