name: Push to ECR

on:
  push:
    branches:
           - main
      

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Download secure file
        run: echo "${{ secrets.SECRET_NAME }}" > server.xml 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9
        with:
          projectBaseDir: .

      
