name: Push to ECR

on:
  push:
    branches:
      

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-aws-region>

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Download secure file
        run: |
	 echo "${{ secrets.SECRET_NAME }}" > server.xml 

      - name: Setup SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: <your-sonarcloud-organization>
          project: <your-sonarcloud-project>
          token: ${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	    - name: Set up JDK
        uses: maven/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./java-maven

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./java-maven/target/my-artifact.jar
